version: "3.7"

services:
  app:
    build: .
    ports:
      - "80:3000"
    volumes:
      - .:/app:delegated
      - bundle_cache:/usr/local/bundle:cached
      - node_modules:/app/node_modules:cached

volumes:
  bundle_cache:
  node_modules:
